import Head from 'next/head'
import Navbar from '../components/Navbar'
import Banner from '../components/Banner'
import requests from '../utils/requests'
import { fetch } from 'next/dist/compiled/@edge-runtime/primitives/fetch'
import Row from '../components/Row'





const Home =({
               netflixOriginals,
               actionMovies,
               comedyMovies,
               horrorMovies,
               romanceMovies,
               topRated,
               trendingNow,
             }) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Banner netflixOriginals={netflixOriginals}/>
      <main>
        <Row
          rowID='1'
          title={'Trending Now'}
          allMovies={trendingNow}
        />
        <Row
          rowID='2'
          title={'Top Movies'}
          allMovies={topRated}
        />
        <Row
          rowID='3'
          title={'Horror Movies'}
          allMovies={horrorMovies}
        />
        <Row
          rowID='4'
          title={'Action Movies'}
          allMovies={actionMovies}
        />
        <Row
          rowID='5'
          title={'Comedy Movies'}
          allMovies={comedyMovies}
        />
        <Row
          rowID='5'
          title={'Romance Movies'}
          allMovies={romanceMovies}
        />
       
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
  ])
  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
    }
  }
  
}

export default Home

